# Generated by Django 4.1.7 on 2023-05-09 00:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalFinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                    ),
                ),
                ("cash_on_hand", models.IntegerField(null=True)),
                ("savings_account", models.IntegerField(null=True)),
                ("cash", models.IntegerField(null=True)),
                ("marketable_securities", models.IntegerField(null=True)),
                ("total_liquid_assets", models.IntegerField(null=True)),
                ("primary_residence", models.IntegerField(null=True)),
                ("ira_401k", models.IntegerField(null=True)),
                ("life_insurance", models.IntegerField(null=True)),
                ("notes_receivable", models.IntegerField(null=True)),
                ("business_values", models.IntegerField(null=True)),
                ("automobiles", models.IntegerField(null=True)),
                ("personal_property", models.IntegerField(null=True)),
                ("total_other_assets", models.IntegerField(null=True)),
                ("total_assets", models.IntegerField(null=True)),
                ("total_re_mortgage", models.IntegerField(null=True)),
                ("accounts_payable", models.IntegerField(null=True)),
                ("notes_payable", models.IntegerField(null=True)),
                ("installment_accounts_auto", models.IntegerField(null=True)),
                ("installment_accounts_other", models.IntegerField(null=True)),
                ("installment_accounts", models.IntegerField(null=True)),
                ("total_liabilities", models.IntegerField(null=True)),
                ("net_worth", models.IntegerField(null=True)),
                ("grand_total", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingYears",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=200)),
                ("num_of_locations", models.IntegerField()),
                ("total_sales", models.IntegerField()),
                ("food_cost", models.IntegerField()),
                ("labor_cost", models.IntegerField()),
                ("total_cost_of_goods_sold", models.IntegerField(default=0)),
                ("admin_and_general", models.IntegerField()),
                ("rands_marketing", models.IntegerField()),
                ("facilities", models.IntegerField()),
                ("total_other_operative_expenses", models.IntegerField(default=0)),
                ("total_operative_expenses", models.IntegerField(default=0)),
                ("income_before_fix_expense", models.IntegerField(default=0)),
                ("property_tax", models.IntegerField()),
                ("insurance", models.IntegerField()),
                ("reserve", models.IntegerField()),
                ("total_fix_expenses", models.IntegerField(default=0)),
                ("net_income_before_interest_and_tax", models.IntegerField(default=0)),
                ("percentages", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialFlashReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("years_in_current_business", models.IntegerField()),
                ("current_business_structure", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="financial_flash_report_pdfs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finance_review", models.CharField(max_length=200)),
                ("operating_company", models.CharField(max_length=200)),
                ("parent_company", models.CharField(max_length=200)),
                ("business_owners", models.CharField(max_length=200)),
                ("primary_business_address", models.CharField(max_length=200)),
                ("proposed_loan_needs", models.CharField(max_length=200)),
                ("list_of_report_outcomes", models.TextField(max_length=40000)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
