# Generated by Django 4.1.7 on 2023-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialflashreport",
            name="business_id",
            field=models.IntegerField(null=True),
        ),
    ]
