# Generated by Django 4.1.7 on 2023-03-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financeReview", models.CharField(max_length=200)),
                ("operatingCompany", models.CharField(max_length=200)),
                ("parentCompany", models.CharField(max_length=200)),
                ("businessOwners", models.CharField(max_length=200)),
                ("primaryBusinessAddress", models.CharField(max_length=200)),
                ("listOfReportOutcomes", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="SearchLog",
        ),
    ]
