# Generated by Django 4.1.7 on 2023-04-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingyears",
            name="income_before_fix_expense",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="net_income_before_interest_and_tax",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="percentages",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="total_cost_of_goods_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="total_fix_expenses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="total_operative_expenses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatingyears",
            name="total_other_operative_expenses",
            field=models.IntegerField(default=0),
        ),
    ]
