# Generated by Django 4.1.7 on 2023-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinformation",
            name="locations",
            field=models.CharField(default="something", max_length=200),
            preserve_default=False,
        ),
    ]
