# Generated by Django 4.1.7 on 2023-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_basicinformation_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialflashreport",
            name="consolidated",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="financialflashreport",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="financialflashreport",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="financialflashreport",
            name="current_business_structure",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="financialflashreport",
            name="date_of_statement",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="financialflashreport",
            name="owner_name",
            field=models.CharField(max_length=255),
        ),
    ]
