# Generated by Django 4.1.7 on 2023-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_operatingyears_income_before_fix_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinformation",
            name="proposed_loan_needs",
            field=models.CharField(max_length=200),
        ),
    ]
