# Generated by Django 4.1.7 on 2023-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_basicinformation_delete_searchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxYears",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=200)),
                ("numOfLocations", models.CharField(max_length=200)),
                ("totalSales", models.CharField(max_length=200)),
                ("foodCost", models.CharField(max_length=200)),
                ("laborCost", models.CharField(max_length=200)),
                ("adminAndGeneral", models.CharField(max_length=200)),
                ("randsMarketing", models.CharField(max_length=200)),
                ("incomeBeforeFixExpense", models.CharField(max_length=200)),
                ("propertyTax", models.CharField(max_length=200)),
                ("insurance", models.CharField(max_length=200)),
                ("reserve", models.CharField(max_length=200)),
            ],
        ),
    ]
