# Generated by Django 4.1.7 on 2023-03-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_taxyears"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxyears",
            old_name="area",
            new_name="state",
        ),
    ]
