# Generated by Django 4.1.7 on 2023-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_rename_area_taxyears_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalFinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cash", models.CharField(max_length=200)),
                ("marketable_securities", models.CharField(max_length=200)),
                ("total_liquid_assets", models.CharField(max_length=200)),
                ("real_estate", models.CharField(max_length=200)),
                ("primary_residence", models.CharField(max_length=200)),
                ("total_real_estate", models.CharField(max_length=200)),
                ("ira_401k", models.CharField(max_length=200)),
                ("life_insurance", models.CharField(max_length=200)),
                ("notes_receivable", models.CharField(max_length=200)),
                ("business_values", models.CharField(max_length=200)),
                ("automobiles", models.CharField(max_length=200)),
                ("personal_property", models.CharField(max_length=200)),
                ("total_other_assets", models.CharField(max_length=200)),
                ("total_assets", models.CharField(max_length=200)),
                ("primary_residence_re_mortgage", models.CharField(max_length=200)),
                ("total_re_mortgage", models.CharField(max_length=200)),
                ("notes_payable", models.CharField(max_length=200)),
                ("installment_accounts", models.CharField(max_length=200)),
                ("total_liabilities", models.CharField(max_length=200)),
                ("net_worth", models.CharField(max_length=200)),
                ("grand_total", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("years_in_current_business", models.CharField(max_length=200)),
                ("current_business_structure", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="businessOwners",
            new_name="business_owners",
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="financeReview",
            new_name="finance_review",
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="listOfReportOutcomes",
            new_name="list_of_report_outcomes",
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="operatingCompany",
            new_name="operating_company",
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="parentCompany",
            new_name="parent_company",
        ),
        migrations.RenameField(
            model_name="basicinformation",
            old_name="primaryBusinessAddress",
            new_name="primary_business_address",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="adminAndGeneral",
            new_name="admin_and_general",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="foodCost",
            new_name="food_cost",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="incomeBeforeFixExpense",
            new_name="income_before_fix_expense",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="laborCost",
            new_name="labor_cost",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="numOfLocations",
            new_name="num_of_locations",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="propertyTax",
            new_name="property_tax",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="randsMarketing",
            new_name="rands_marketing",
        ),
        migrations.RenameField(
            model_name="taxyears",
            old_name="totalSales",
            new_name="total_sales",
        ),
    ]
